name: "[CI] Test"

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUBY_VERSION: 3.2.2
  DISABLE_SPRING: 1
  NODE_VERSION: 18.17.1

jobs:
  test-report:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres

      redis:
        image: redis:3.2-alpine
        ports: ["6379:6379"]

    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
      RAILS_ENV: test
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: nanasess/setup-chromedriver@v2

      - run: |
          sudo apt install wkhtmltopdf imagemagick 7zip

      - name: Setup Database
        run: bundle exec rake test_app

      - name: Precompile assets
        working-directory: ./spec/decidim_dummy_app/
        env:
          BUNDLE_GEMFILE: ../../Gemfile
        run: |
          npm install
          bundle exec rake assets:precompile

      - name: Run RSpec
        run: bundle exec rspec
        env:
          CI: 1

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: ./tmp/screenshots
          if-no-files-found: ignore
          overwrite: true
